// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAmvKfDpCb9jRvobX2clbOIxqwSI4ClmKI',
//     appId: '1:105781102422:web:49c0284950f348c30bb8f7',
//     messagingSenderId: '105781102422',
//     projectId: 'bidbazar-80691',
//     authDomain: 'bidbazar-80691.firebaseapp.com',
//     storageBucket: 'bidbazar-80691.appspot.com',
//     measurementId: 'G-2LL4QSJLEY',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAVEoYDhNvqyPN3zCuUC2ofk9K3I3_6pbs',
//     appId: '1:105781102422:android:7174b2d56b372a2e0bb8f7',
//     messagingSenderId: '105781102422',
//     projectId: 'bidbazar-80691',
//     storageBucket: 'bidbazar-80691.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCGs6uiNI6rwFbl7VdppZlNG9Jwi8pmSAc',
//     appId: '1:105781102422:ios:32b8d2b995eb209d0bb8f7',
//     messagingSenderId: '105781102422',
//     projectId: 'bidbazar-80691',
//     storageBucket: 'bidbazar-80691.appspot.com',
//     iosBundleId: 'com.example.bidbazar',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCGs6uiNI6rwFbl7VdppZlNG9Jwi8pmSAc',
//     appId: '1:105781102422:ios:9177b756d21d19360bb8f7',
//     messagingSenderId: '105781102422',
//     projectId: 'bidbazar-80691',
//     storageBucket: 'bidbazar-80691.appspot.com',
//     iosBundleId: 'com.example.bidbazar.RunnerTests',
//   );
// }
